# CI/CD 워크플로 (Continuous Integration / Continuous Deployment)
name: CI/CD Pipeline for Backend

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: cloudnative-backend

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/cloudnative-backend
      K8S_MANIFEST_PATH: k8s/deployment.yaml

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - run: mvn -B package --file pom.xml -DskipTests

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Image Tag
        id: image_tag
        run: |
          echo "tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPO }}:${{ steps.image_tag.outputs.tag }}, ${{ env.IMAGE_REPO }}:latest

      - name: Update K8s Manifest
        run: |
          sed -i "s|${{ env.IMAGE_REPO }}:.*|${{ env.IMAGE_REPO }}:${{ steps.image_tag.outputs.tag }}|g" ${{ env.K8S_MANIFEST_PATH }}

      - name: Commit Manifest Change
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          # 변경사항 없으면 종료 (에러 X)
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git add ${{ env.K8S_MANIFEST_PATH }}
          git commit -m "chore(ci): update deployment image to ${{ steps.image_tag.outputs.tag }}"
          git push

